esphome:
  name: bwss1
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "nome_wifi"
  password: "password_wifi"

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "Pulsante BW SS1"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "BW SS1 Relay"
    pin: GPIO5
    id: relay

status_led:
  pin:
    number: GPIO4
    inverted: yes
    
