esphome:
  name: esempioesphome

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

web_server:
  port: 80
  

# It is highly recommended to use secrets
wifi:
  ssid: !secret ssid
  password: !secret password




  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Myvirtualbutton Fallback Hotspot"
    password: !secret password

captive_portal:



switch:
  - platform: template
    name: "Faretti Salagiochi"
    icon: "mdi:wall-sconce-flat"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay
  
  - platform: gpio
    id: relay
    pin: GPIO12
