esphome:
  name: tapparella
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "Nome_wifi"
  password: "password_wifi"

api:
  reboot_timeout: 0s
  
logger:

ota:

web_server:
  port: 80

binary_sensor:
#gpio per pulsante apri/stop/chiudi
- platform: gpio
  pin:
    number: D1
#    inverted: true
    mode: INPUT_PULLUP
  filters:
    - delayed_on: 10ms
  id: pulsante
  on_press:
    then:
      # logica per passare tra le varie fasi: apri->stop->chiudi->stop->...
      - lambda: |
          if (id(tapparella).current_operation == COVER_OPERATION_IDLE) {
            // Cover is idle, check current state and either open or close cover.
            if (id(tapparella).is_fully_closed()) {
              id(tapparella).open();
            } else {
              id(tapparella).close();
            }
          } else {
            // Cover is opening/closing. Stop it.
            id(tapparella).stop();
          }

switch:
- platform: gpio
#GPIO x relè apri
  pin: D8
  inverted: true
  interlock: &interlock [open_cover, close_cover]
  id: open_cover
- platform: gpio
#GPIO x relè chiudi
  pin: D4
  inverted: true
  interlock: *interlock
  id: close_cover

cover:
- platform: time_based
  name: "Tapparella Studio"
  id: tapparella
  open_action:
    - switch.turn_on: open_cover
  open_duration: 18s
  close_action:
    - switch.turn_on: close_cover
  close_duration: 17s
  stop_action:
    - switch.turn_off: open_cover
    - switch.turn_off: close_cover
    
