esphome:
  name: tastovirtualescrivania

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

web_server:
  port: 80
  
# It is highly recommended to use secrets
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

switch:
  - platform: template
    name: "Faretto parete"
    icon: "mdi:wall-sconce-flat"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay
  
  - platform: gpio
    id: relay
    pin: GPIO12


    