esphome:
  name: tastovirtualescrivania

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  port: 80
  auth:
    username: !secret web_server_username
    password: !secret web_server_password

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  

# It is highly recommended to use secrets
wifi:
  ssid:     !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

time:
  - platform: sntp
    id: my_time
    timezone: Europe/Rome

binary_sensor:
  - platform: status
    name: EspHome Node Status

mqtt:
  broker:   !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery: true

switch:
  - platform: restart
    name: EspHome Node Restart
  - platform: template
    name: "Faretto parete"
    icon: "mdi:wall-sconce-flat"
    optimistic: true
    id: fakebutton
    turn_on_action:
    - switch.turn_on: relay
    turn_off_action:
    - switch.turn_off: relay
  
  - platform: gpio
    id: relay
    pin: GPIO12


text_sensor:
  - platform: version
    name: EspHome Node Version
    hide_timestamp: true    
  - platform: wifi_info
    ip_address:
      name: EspHome Node IP Address      


sensor:
  - platform: wifi_signal
    name: Wi-Fi Signal
    update_interval: 30s       